### PR TITLE
hacktoberfest-2022

### PR DESCRIPTION
**Pull request by Naisargika1402**
please add my file to in your repository with label hacktoberfest

### CODE REVIEW

**Comment by Naisargika1402** [comment]
I have added the code twice by mistakenly.
Can you still please merge my pull request?

**Review by pranavgoel29 — CHANGES_REQUESTED** [review]
Delete the extra file

**Comment by Naisargika1402** [comment]
> Delete the extra file

DONE!

**Comment by Naisargika1402** [comment]
Done 👍

**Pull request merged**
